/*
 * This source file was generated by the Gradle 'init' task
 */
package com.myspring.app

import com.myspring.app.bean.UserConfig
import org.apache.catalina.core.ApplicationContext
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.support.ClassPathXmlApplicationContext

@SpringBootApplication
class App {
    
    static void main(String[] args) {
        SpringApplication.run(App.class, args);

        ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext.xml");
        UserConfig cotroller = context.getBean("userConfigBean");
    }
}
